//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_exam : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Washroom
        {
            get
            {
                return SteamVR_Actions.exam_Washroom;
            }
        }
        
        public virtual SteamVR_Action_Boolean Hint
        {
            get
            {
                return SteamVR_Actions.exam_Hint;
            }
        }
        
        public virtual SteamVR_Action_Boolean HideAndShowSkills
        {
            get
            {
                return SteamVR_Actions.exam_HideAndShowSkills;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextQuestion
        {
            get
            {
                return SteamVR_Actions.exam_NextQuestion;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrevQuestion
        {
            get
            {
                return SteamVR_Actions.exam_PrevQuestion;
            }
        }
    }
}
